version: "3.8"
services:
  #Default standard ai python base image
  python-base:
    build:
      dockerfile: ./Docker/python.dockerfile
      context: .
    container_name: python-base
    command: "tail -f /dev/null"
    restart: always
    environment:
      TEST: ${TEST:-"docker-compose dev"}
  pdm-base:
    build:
      dockerfile: ./Docker/pdm.dockerfile
      context: .
    container_name: pdm-base
    command: "tail -f /dev/null"
    restart: always
    environment:
      TEST: ${TEST:-"docker-compose dev"}