name: deploy_images
on:
    push
    # release:
    #     types: [published]

jobs:
    publish-docker-images:
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3
            
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            
            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v3
              with:
                images: ghcr.io/pythonbiellagroup/python-base
      
            - name: Build and push Docker image
              uses: docker/build-push-action@v3
              with:
                context: .
                file: ./Docker/python.dockerfile
                push: true
                target: final
                tags: ghcr.io/pythonbiellagroup/python-base:${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
            # Custom job to publish the image
            # - name: Build and push python base
            #   run: |
            #     docker build ./Docker/python.dockerfile --tag ghcr.io/PythonBiellaGroup/python-base:latest
            #     docker run ghcr.io/PythonBiellaGroup/python-base:${{ steps.meta.outputs.tags }}
            #     docker push ghcr.io/PythonBiellaGroup/python-base:${{ steps.meta.outputs.tags }}