name: deploy_images
on:
    release:
        types: [published]

jobs:
    publish-docker-images:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3
            
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                registry: ghcr.io
                username: ${{ secrets.GITHUB_USERNAME }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push python base
              run: |
                docker build ./Docker/python.dockerfile --tag ghcr.io/PythonBiellaGroup/python-base:latest
                docker run ghcr.io/PythonBiellaGroup/python-base:latest
                docker push ghcr.io/PythonBiellaGroup/python-base:latest